# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpartanMessenger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpartanMessenger.proto',
  package='messenger',
  syntax='proto3',
  serialized_pb=_b('\n\x16SpartanMessenger.proto\x12\tmessenger\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\" \n\x0cGroupRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\"-\n\rGroupResponse\x12\r\n\x05group\x18\x01 \x01(\t\x12\r\n\x05users\x18\x02 \x01(\t\"\x1c\n\x0cLoginRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\"o\n\x0bSendMessage\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1c\n\x08Response\x12\x10\n\x08messages\x18\x01 \x01(\t\"+\n\x07Receive\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\"0\n\x0c\x43hatResponse\x12\x10\n\x08messages\x18\x02 \x01(\x0c\x12\x0e\n\x06sender\x18\x03 \x01(\t2\xf0\x01\n\tMessenger\x12\x36\n\x07message\x12\x16.messenger.SendMessage\x1a\x13.messenger.Response\x12\x38\n\x07receive\x12\x12.messenger.Receive\x1a\x17.messenger.ChatResponse0\x01\x12\x35\n\x05login\x12\x17.messenger.LoginRequest\x1a\x13.messenger.Response\x12:\n\x05group\x12\x17.messenger.GroupRequest\x1a\x18.messenger.GroupResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_GROUPREQUEST = _descriptor.Descriptor(
  name='GroupRequest',
  full_name='messenger.GroupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userName', full_name='messenger.GroupRequest.userName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=129,
)


_GROUPRESPONSE = _descriptor.Descriptor(
  name='GroupResponse',
  full_name='messenger.GroupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='messenger.GroupResponse.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='users', full_name='messenger.GroupResponse.users', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=176,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='messenger.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='messenger.LoginRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=206,
)


_SENDMESSAGE = _descriptor.Descriptor(
  name='SendMessage',
  full_name='messenger.SendMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='messenger.SendMessage.message', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='messenger.SendMessage.sender', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='messenger.SendMessage.receiver', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='messenger.SendMessage.timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=319,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='messenger.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='messenger.Response.messages', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=349,
)


_RECEIVE = _descriptor.Descriptor(
  name='Receive',
  full_name='messenger.Receive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='messenger.Receive.sender', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='messenger.Receive.receiver', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=394,
)


_CHATRESPONSE = _descriptor.Descriptor(
  name='ChatResponse',
  full_name='messenger.ChatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='messenger.ChatResponse.messages', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='messenger.ChatResponse.sender', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=444,
)

_SENDMESSAGE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['GroupRequest'] = _GROUPREQUEST
DESCRIPTOR.message_types_by_name['GroupResponse'] = _GROUPRESPONSE
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['SendMessage'] = _SENDMESSAGE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Receive'] = _RECEIVE
DESCRIPTOR.message_types_by_name['ChatResponse'] = _CHATRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GroupRequest = _reflection.GeneratedProtocolMessageType('GroupRequest', (_message.Message,), dict(
  DESCRIPTOR = _GROUPREQUEST,
  __module__ = 'SpartanMessenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.GroupRequest)
  ))
_sym_db.RegisterMessage(GroupRequest)

GroupResponse = _reflection.GeneratedProtocolMessageType('GroupResponse', (_message.Message,), dict(
  DESCRIPTOR = _GROUPRESPONSE,
  __module__ = 'SpartanMessenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.GroupResponse)
  ))
_sym_db.RegisterMessage(GroupResponse)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'SpartanMessenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

SendMessage = _reflection.GeneratedProtocolMessageType('SendMessage', (_message.Message,), dict(
  DESCRIPTOR = _SENDMESSAGE,
  __module__ = 'SpartanMessenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.SendMessage)
  ))
_sym_db.RegisterMessage(SendMessage)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'SpartanMessenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.Response)
  ))
_sym_db.RegisterMessage(Response)

Receive = _reflection.GeneratedProtocolMessageType('Receive', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVE,
  __module__ = 'SpartanMessenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.Receive)
  ))
_sym_db.RegisterMessage(Receive)

ChatResponse = _reflection.GeneratedProtocolMessageType('ChatResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHATRESPONSE,
  __module__ = 'SpartanMessenger_pb2'
  # @@protoc_insertion_point(class_scope:messenger.ChatResponse)
  ))
_sym_db.RegisterMessage(ChatResponse)



_MESSENGER = _descriptor.ServiceDescriptor(
  name='Messenger',
  full_name='messenger.Messenger',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=447,
  serialized_end=687,
  methods=[
  _descriptor.MethodDescriptor(
    name='message',
    full_name='messenger.Messenger.message',
    index=0,
    containing_service=None,
    input_type=_SENDMESSAGE,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='receive',
    full_name='messenger.Messenger.receive',
    index=1,
    containing_service=None,
    input_type=_RECEIVE,
    output_type=_CHATRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='login',
    full_name='messenger.Messenger.login',
    index=2,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='group',
    full_name='messenger.Messenger.group',
    index=3,
    containing_service=None,
    input_type=_GROUPREQUEST,
    output_type=_GROUPRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGER)

DESCRIPTOR.services_by_name['Messenger'] = _MESSENGER

# @@protoc_insertion_point(module_scope)
